name: 'Extract Umbraco version'

on:
  push:
    branches:
      - 'feature/extract-umb-version'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  extractVersion:
    runs-on: ubuntu-latest
    name: 'Extract Umbraco Version'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Version
        id: getversion
        uses: m-ringler/get-xpath@v3
        with:
          xml-file: 'Test.csproj'
          xpath: "string(//PackageReference[@Include='Umbraco.Cms']/@Version)"
      - uses: release-drafter/release-drafter@v5
        with:
          header: |
            ## Dependencies
            
            ### Umbraco Version ${{ steps.getversion.outputs.info }}\
          footer: |
            ## Dependencies
            
            ### Umbraco Version ${{ steps.getversion.outputs.info }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}